services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # RabbitMQ Management Plugin Web UI
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: unless-stopped
